### PR TITLE
remove mirgecom requirement in setup.py, change mc branch to production

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Review by MTCam — COMMENTED** [review]
Why shouldn't the driver install require mirgecom?

**Comment by anderson2981** [comment]
I've diabled the check for now. I don't understand exactly what's wrong with it. Seems logical that the driver that uses mirgecom should depend on mirgecom.

**Comment by anderson2981** [comment]
> 

So less of a "this package requries mirgecom" and more of a "install mirgecom if it's not available".

**Comment by matthiasdiener** [comment]
> So less of a "this package requries mirgecom" and more of a "install mirgecom if it's not available".

Yes, I think so.

**Comment by anderson2981** [comment]
changed made in main.

**Pull request closed without merging**
